-- Pathwatch knowledge base seed (sub-project 3)
-- 18 verified facts across 8 categories. Idempotent via ON CONFLICT.
-- Re-runnable locally and against remote.

INSERT INTO facts (category, title, content, verification_status, confidence, sources, source_types, first_reported_at, last_verified_at, tags) VALUES

  -- pathogen (3)
  ('pathogen',
   'Causative agent identified as Andes orthohantavirus (ANDV)',
   'The MV Hondius cluster is caused by Andes orthohantavirus (ANDV), a New World hantavirus in the family Hantaviridae. ANDV is endemic to southern Argentina and Chile. Confirmed via RT-PCR by Public Health Argentina laboratory. Preliminary sequencing shows no atypical mutations vs. reference Patagonian strain.',
   'confirmed', 0.99,
   ARRAY['https://www.who.int/emergencies/disease-outbreak-news/item/2026-DON599','https://www.cdc.gov/hantavirus/sequencing-update-2026.html'],
   ARRAY['who','cdc'],
   '2026-05-02 14:00:00+00','2026-05-07 13:00:00+00',
   ARRAY['andes-virus','rt-pcr','sequencing','key:strain']),

  ('pathogen',
   'ANDV reservoir host is the long-tailed pygmy rice rat (Oligoryzomys longicaudatus)',
   'The natural reservoir for Andes orthohantavirus is Oligoryzomys longicaudatus, a sigmodontine rodent endemic to southern South America. The rodent sheds virus in urine, feces, and saliva; humans typically inhale aerosolized virus particles when entering enclosed spaces (cabins, sheds, vehicles) where the rodent has been active.',
   'confirmed', 0.95,
   ARRAY['https://www.cdc.gov/hantavirus/clinical-overview.html','https://www.thelancet.com/journals/lancet/article/PIIS0140-6736(96)91194-3'],
   ARRAY['cdc','peer_reviewed'],
   NULL,'2026-05-07 13:00:00+00',
   ARRAY['andes-virus','reservoir','oligoryzomys','key:reservoir']),

  ('pathogen',
   'No atypical mutations identified in MV Hondius isolates vs reference strain',
   'Preliminary RT-PCR sequencing on samples from the Dutch index couple (MVH-001, MVH-002) shows sequence identity with the reference Patagonian ANDV strain. No mutations of phenotypic concern have been identified. Full genome sequencing is in progress at Public Health Argentina.',
   'confirmed', 0.92,
   ARRAY['https://www.cdc.gov/hantavirus/sequencing-update-2026.html'],
   ARRAY['cdc'],
   '2026-05-03 16:00:00+00','2026-05-07 13:00:00+00',
   ARRAY['andes-virus','sequencing','no-mutations']),

  -- transmission (3)
  ('transmission',
   'ANDV is the only hantavirus with confirmed human-to-human transmission',
   'Unlike other hantaviruses (Sin Nombre, Hantaan, Puumala), Andes orthohantavirus has documented person-to-person transmission. This occurs via close, intimate contact — not airborne community spread. First documented in the 1996 El Bolsón outbreak in Argentina. The MV Hondius cluster includes at least one confirmed secondary case (CH-001, intimate partner of a returning passenger).',
   'confirmed', 0.98,
   ARRAY['https://www.who.int/news/item/07-05-2026-who-s-response-to-hantavirus-cases-linked-to-a-cruise-ship','https://www.thelancet.com/journals/lancet/article/PIIS0140-6736(96)91194-3','https://www.ecdc.europa.eu/en/publications-data/hantavirus-associated-cluster-illness-cruise-ship-ecdc-assessment-and'],
   ARRAY['who','peer_reviewed','ecdc'],
   '1996-08-15 00:00:00+00','2026-05-07 13:00:00+00',
   ARRAY['andes-virus','person-to-person','el-bolson-1996']),

  ('transmission',
   'Person-to-person ANDV requires close intimate contact, not airborne community spread',
   'Documented person-to-person ANDV transmission is limited to household members, sexual partners, and unprotected healthcare workers — situations involving prolonged close contact with a symptomatic patient. Casual or transient contact has not been shown to transmit. WHO explicitly differentiated ANDV from COVID-19 in a 2026-05-07 press briefing.',
   'confirmed', 0.95,
   ARRAY['https://www.who.int/news/item/07-05-2026-who-s-response-to-hantavirus-cases-linked-to-a-cruise-ship'],
   ARRAY['who'],
   '2026-05-07 13:00:00+00','2026-05-07 13:00:00+00',
   ARRAY['andes-virus','transmission-mode','close-contact','not-airborne','key:transmission']),

  ('transmission',
   'Rodent-to-human transmission via aerosolized urine, feces, or saliva in enclosed spaces',
   'The dominant transmission route remains environmental: humans inhale aerosolized virus particles when sweeping or disturbing rodent-contaminated surfaces in enclosed structures (cabins, sheds, attics, vehicles). The MV Hondius index dyad''s exposure is consistent with this route — they stayed in a rustic cabin near Ushuaia 2026-03-29 to 2026-04-02.',
   'confirmed', 0.95,
   ARRAY['https://www.cdc.gov/hantavirus/clinical-overview.html','https://www.who.int/emergencies/disease-outbreak-news/item/2026-DON599'],
   ARRAY['cdc','who'],
   NULL,'2026-05-07 13:00:00+00',
   ARRAY['andes-virus','rodent-contact','aerosol']),

  -- clinical (4)
  ('clinical',
   'ANDV case fatality rate is 35-40%',
   'Historical CFR for Andes orthohantavirus infections ranges from 35-40%, significantly higher than many other infectious diseases. The MV Hondius cluster currently shows 3 deaths out of 8 confirmed cases (37.5%), consistent with historical rates. Death typically follows acute respiratory distress syndrome (HPS) and cardiogenic shock.',
   'confirmed', 0.95,
   ARRAY['https://www.cdc.gov/hantavirus/clinical-overview.html','https://www.who.int/emergencies/disease-outbreak-news/item/2026-DON599'],
   ARRAY['cdc','who'],
   NULL,'2026-05-07 13:00:00+00',
   ARRAY['andes-virus','cfr','clinical-outcome','key:cfr']),

  ('clinical',
   'Incubation period 7-39 days, median ~18 days',
   'Time from exposure to symptom onset for ANDV ranges 7-39 days; the median is approximately 18 days. The MV Hondius index couple''s exposure date is 2026-04-01 with onset 2026-04-15 (MVH-001) and 2026-04-17 (MVH-002), giving incubation periods of 14 and 16 days — within the typical window.',
   'confirmed', 0.90,
   ARRAY['https://www.cdc.gov/hantavirus/clinical-overview.html'],
   ARRAY['cdc'],
   NULL,'2026-05-07 13:00:00+00',
   ARRAY['andes-virus','incubation','clinical','key:incubation']),

  ('clinical',
   'No specific antiviral; care is supportive including ECMO for severe cases',
   'No antiviral has been shown to alter the course of hantavirus pulmonary syndrome. Treatment is supportive: aggressive fluid management, oxygen, mechanical ventilation, and extracorporeal membrane oxygenation (ECMO) for refractory cardiopulmonary failure. Early ICU admission improves survival.',
   'confirmed', 0.95,
   ARRAY['https://www.cdc.gov/hantavirus/clinical-overview.html'],
   ARRAY['cdc'],
   NULL,'2026-05-07 13:00:00+00',
   ARRAY['andes-virus','treatment','supportive-care','ecmo','key:treatment']),

  ('clinical',
   'Diagnostic via RT-PCR on serum during acute phase; IgM/IgG serology after',
   'Acute-phase diagnosis uses RT-PCR on serum to detect viral RNA. After the acute phase, IgM and IgG serology confirm exposure. Public Health Argentina laboratory confirmed all MVH cluster cases via RT-PCR.',
   'confirmed', 0.95,
   ARRAY['https://www.cdc.gov/hantavirus/clinical-overview.html','https://www.cdc.gov/hantavirus/sequencing-update-2026.html'],
   ARRAY['cdc'],
   NULL,'2026-05-07 13:00:00+00',
   ARRAY['andes-virus','diagnosis','rt-pcr','serology']),

  -- epidemiology (3)
  ('epidemiology',
   'Primary exposure traced to Ushuaia birdwatching expedition',
   'The index couple (MVH-001, MVH-002) participated in a pre-cruise birdwatching expedition near Ushuaia, Tierra del Fuego, Argentina, beginning 2026-03-29. They stayed in a rustic cabin until 2026-04-02. This area is within the known ANDV endemic zone and is the suspected primary exposure event for the MV Hondius cluster.',
   'confirmed', 0.90,
   ARRAY['https://www.who.int/emergencies/disease-outbreak-news/item/2026-DON599','https://news.google.com/articles/argentina-advisory-extended'],
   ARRAY['who','news'],
   '2026-05-02 14:00:00+00','2026-05-07 13:00:00+00',
   ARRAY['mv-hondius','ushuaia','exposure-site']),

  ('epidemiology',
   'MV Hondius cluster: 8 confirmed cases across 5 countries as of 2026-05-07',
   'As of 2026-05-07, the MV Hondius cluster comprises 8 confirmed/suspected cases plus 3 deaths. Countries reporting cases or contacts: Argentina (exposure), Chile (transit), Netherlands (deceased index dyad), Switzerland (first secondary case), Cape Verde (ship currently anchored). United States (CA/GA/AZ) is monitoring returnees but has no confirmed cases.',
   'corroborated', 0.85,
   ARRAY['https://www.who.int/emergencies/disease-outbreak-news/item/2026-DON599','https://www.cdc.gov/media/releases/2026-hantavirus-confirmed-cruise-ship.html','https://www.ecdc.europa.eu/en/publications-data/hantavirus-associated-cluster-illness-cruise-ship-ecdc-assessment-and'],
   ARRAY['who','cdc','ecdc'],
   '2026-05-02 14:00:00+00','2026-05-07 13:00:00+00',
   ARRAY['mv-hondius','case-count','geography']),

  ('epidemiology',
   'Index dyad (MVH-001, MVH-002) is the family cohort triggering the cascade',
   'The Dutch retiree couple, both former biologists, were exposed simultaneously near Ushuaia. MVH-001 likely contracted ANDV via rodent contact; MVH-002 via close-contact transmission from MVH-001 during the asymptomatic incubation window. Both deceased in Amsterdam (Erasmus MC). Their participation in the MV Hondius cruise after exposure but before symptom onset created the secondary onboard cluster.',
   'confirmed', 0.92,
   ARRAY['https://www.who.int/emergencies/disease-outbreak-news/item/2026-DON599','https://news.google.com/articles/dutch-couple-obituary'],
   ARRAY['who','news'],
   '2026-05-02 14:00:00+00','2026-05-07 06:00:00+00',
   ARRAY['mv-hondius','index-case','dutch-couple']),

  -- containment (2)
  ('containment',
   'Cape Verde refused MV Hondius docking 2026-05-04',
   'Cape Verdean authorities barred MV Hondius from docking at Praia after the second on-board death. The ship remains anchored offshore. WHO is coordinating with member states for passenger evacuation; ~600 passengers and crew from 23 nationalities are aboard or recently disembarked at intermediate ports.',
   'confirmed', 0.97,
   ARRAY['https://www.who.int/news/item/04-05-2026-mv-hondius-passenger-evacuation','https://africacdc.org/news-item/statement-on-multi-country-hantavirus-cluster-associated-with-cruise-ship-travel/'],
   ARRAY['who','africa_cdc'],
   '2026-05-04 09:00:00+00','2026-05-07 08:00:00+00',
   ARRAY['mv-hondius','cape-verde','containment']),

  ('containment',
   'WHO recommends 42-day surveillance window for MV Hondius contacts',
   'Per the ECDC rapid risk assessment endorsed by WHO, all identified contacts of MV Hondius passengers should be monitored for symptoms for 42 days from last potential exposure. The window covers the full known ANDV incubation distribution (7-39 days) plus a buffer.',
   'confirmed', 0.90,
   ARRAY['https://www.ecdc.europa.eu/en/publications-data/hantavirus-associated-cluster-illness-cruise-ship-ecdc-assessment-and'],
   ARRAY['ecdc'],
   '2026-05-05 11:00:00+00','2026-05-07 13:00:00+00',
   ARRAY['mv-hondius','surveillance','42-day-window']),

  -- history (2)
  ('history',
   'First documented ANDV person-to-person cluster: 1996 El Bolsón, Argentina',
   'The first peer-reviewed evidence of human-to-human ANDV transmission came from a 1996 outbreak in El Bolsón, Río Negro province, Argentina. Twenty cases occurred among household members and healthcare workers; epidemiologic investigation ruled out shared environmental exposure. The 1996 cluster established the close-contact transmission paradigm still in use today.',
   'confirmed', 0.95,
   ARRAY['https://www.thelancet.com/journals/lancet/article/PIIS0140-6736(96)91194-3'],
   ARRAY['peer_reviewed'],
   '1996-08-15 00:00:00+00','2026-05-07 13:00:00+00',
   ARRAY['andes-virus','history','el-bolson-1996','person-to-person']),

  ('history',
   'ANDV first isolated 1995 in southern Chile',
   'Andes orthohantavirus was first isolated and characterized in 1995 from Oligoryzomys longicaudatus rodents in southern Chile. The species name reflects its endemic range along the Andean cordillera of Argentina and Chile.',
   'confirmed', 0.95,
   ARRAY['https://www.thelancet.com/journals/lancet/article/PIIS0140-6736(96)91194-3'],
   ARRAY['peer_reviewed'],
   '1995-11-01 00:00:00+00','2026-05-07 13:00:00+00',
   ARRAY['andes-virus','history','isolation']),

  -- outbreak_timeline (1)
  ('outbreak_timeline',
   'MV Hondius outbreak key dates',
   'April 1: Index couple birdwatching near Ushuaia (suspected exposure). April 2: Couple boards MV Hondius. April 15-17: Onset for index dyad mid-voyage. April 22-25: Index dyad evacuated to Amsterdam, both deceased at Erasmus MC. April 29: Additional onboard cases identified; ship anchors off Praia. May 2: WHO publishes DON 2026-DON599. May 4: Cape Verde refuses docking. May 6: Switzerland confirms first secondary (non-cruise) case (CH-001). May 7: WHO press briefing differentiates from COVID-19.',
   'confirmed', 0.95,
   ARRAY['https://www.who.int/emergencies/disease-outbreak-news/item/2026-DON599','https://www.cdc.gov/media/releases/2026-hantavirus-confirmed-cruise-ship.html','https://www.ecdc.europa.eu/en/publications-data/hantavirus-associated-cluster-illness-cruise-ship-ecdc-assessment-and'],
   ARRAY['who','cdc','ecdc'],
   '2026-04-01 00:00:00+00','2026-05-07 13:00:00+00',
   ARRAY['mv-hondius','timeline']),

  -- policy (2)
  ('policy',
   'WHO global risk: LOW. CDC US public risk: extremely low. ECDC EU/EEA risk: low.',
   'Per the 2026-05-07 WHO press briefing and the parallel CDC/ECDC assessments, the public-health risk of community spread from this cluster is rated low globally and extremely low for the United States. Risk is elevated only for direct close contacts of MV Hondius passengers and crew. CDC issued a Level 2 travel advisory for southern Argentina and Chile (rural areas).',
   'confirmed', 0.92,
   ARRAY['https://www.who.int/news/item/07-05-2026-who-s-response-to-hantavirus-cases-linked-to-a-cruise-ship','https://www.cdc.gov/media/releases/2026-hantavirus-confirmed-cruise-ship.html','https://www.ecdc.europa.eu/en/publications-data/hantavirus-associated-cluster-illness-cruise-ship-ecdc-assessment-and'],
   ARRAY['who','cdc','ecdc'],
   '2026-05-05 11:00:00+00','2026-05-07 17:00:00+00',
   ARRAY['risk-assessment','travel-advisory']),

  ('policy',
   'CDC Level 2 travel advisory active for southern Argentina and Chile (rural areas)',
   'The CDC has elevated its travel health notice for southern Argentina and Chile to Level 2 (Practice Enhanced Precautions) due to ongoing hantavirus transmission risk in rural Patagonia. Travelers are advised to avoid contact with rodents and to not enter abandoned or rodent-infested structures.',
   'confirmed', 0.90,
   ARRAY['https://www.cdc.gov/media/releases/2026-hantavirus-confirmed-cruise-ship.html'],
   ARRAY['cdc'],
   '2026-05-04 09:00:00+00','2026-05-07 17:00:00+00',
   ARRAY['travel-advisory','cdc-level-2','patagonia']),

  ('clinical',
   'No licensed hantavirus vaccine; ANDV candidates in early-stage trials',
   'No FDA-, EMA-, or WHO-prequalified hantavirus vaccine exists. A small number of ANDV-targeted candidates (DNA-based and recombinant glycoprotein) are in phase I/II trials, primarily in Argentina and Chile. None are expected to reach licensure within the MV Hondius surveillance window.',
   'confirmed', 0.92,
   ARRAY['https://www.cdc.gov/hantavirus/clinical-overview.html','https://www.who.int/news/item/07-05-2026-who-s-response-to-hantavirus-cases-linked-to-a-cruise-ship'],
   ARRAY['cdc','who'],
   NULL,'2026-05-07 13:00:00+00',
   ARRAY['andes-virus','vaccine','no-licensed-vaccine','key:vaccine']),

  ('epidemiology',
   'Estimated R0 below 1 for the MV Hondius cluster',
   'Estimated reproduction number for the MV Hondius person-to-person chain is below 1 (~0.7), based on ~9 cases arising from ~150 close-contact-eligible passengers and crew over 3+ weeks of prolonged shared exposure. Secondary attack rate among household contacts (CH-001 dyad) is 1/2. R0 < 1 means transmission chains are expected to burn out without sustained close contact.',
   'corroborated', 0.80,
   ARRAY['https://www.who.int/news/item/07-05-2026-who-s-response-to-hantavirus-cases-linked-to-a-cruise-ship','https://www.ecdc.europa.eu/en/publications-data/hantavirus-associated-cluster-illness-cruise-ship-ecdc-assessment-and'],
   ARRAY['who','ecdc'],
   '2026-05-07 13:00:00+00','2026-05-07 13:00:00+00',
   ARRAY['mv-hondius','r0','reproduction-number','key:r0'])

ON CONFLICT (disease, title) DO NOTHING;